# Generated by Django 4.1 on 2022-10-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsptl', '0002_department_doctors_delete_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
